[package]
name = "bedrock_packet_viewer"
version = "0.1.0"
edition = "2021"

[package.metadata.windows]
subsystem = "windows"

[dependencies]
iced = { version = "0.14", features = ["canvas", "tokio", "image"] }
tokio = { version = "1.0", features = ["time"] }
bedrock-client = { git = "https://github.com/ismaileke/bedrock-client.git", branch = "master" }
chrono = "0.4"
open = "5.3.3"
serde_json = "1.0.145"

# Windows build için gerekli
[build-dependencies]
winres = "0.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "wincon", "processenv", "shellapi"] }

# Windows konsolu gizlemek için
[target.'cfg(windows)']
rustflags = ["-C", "link-args=-mwindows"]
